/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package launcherv1v1;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author mgarr
 */
public class game extends javax.swing.JFrame {

    /**
     * Creates new form game
     */
    public game() {
        initComponents();
        this.setLocationRelativeTo(null);

        JLabel[] iconolabels = {icon0, icon1, icon2, icon3, icon4, icon5, icon6, icon7, icon8, icon9, icon10, icon11, icon12, icon13};
        for (int i = 0; i < iconolabels.length; i++) {
            SetImageLabel(iconolabels[i], "src/escudos/LauncherButton" + i + ".png");
            addMouseListeners(iconolabels[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        icon0 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        icon5 = new javax.swing.JLabel();
        icon6 = new javax.swing.JLabel();
        icon7 = new javax.swing.JLabel();
        icon9 = new javax.swing.JLabel();
        icon8 = new javax.swing.JLabel();
        icon10 = new javax.swing.JLabel();
        icon11 = new javax.swing.JLabel();
        icon12 = new javax.swing.JLabel();
        icon13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton0.png"))); // NOI18N
        icon0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon0.setMaximumSize(new java.awt.Dimension(90, 90));
        icon0.setMinimumSize(new java.awt.Dimension(90, 90));
        icon0.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton1.png"))); // NOI18N
        icon1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon1.setMaximumSize(new java.awt.Dimension(90, 90));
        icon1.setMinimumSize(new java.awt.Dimension(90, 90));
        icon1.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton2.png"))); // NOI18N
        icon2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon2.setMaximumSize(new java.awt.Dimension(90, 90));
        icon2.setMinimumSize(new java.awt.Dimension(90, 90));
        icon2.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        icon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton3.png"))); // NOI18N
        icon3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon3.setMaximumSize(new java.awt.Dimension(90, 90));
        icon3.setMinimumSize(new java.awt.Dimension(90, 90));
        icon3.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        icon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton4.png"))); // NOI18N
        icon4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon4.setMaximumSize(new java.awt.Dimension(90, 90));
        icon4.setMinimumSize(new java.awt.Dimension(90, 90));
        icon4.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        icon5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton5.png"))); // NOI18N
        icon5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon5.setMaximumSize(new java.awt.Dimension(90, 90));
        icon5.setMinimumSize(new java.awt.Dimension(90, 90));
        icon5.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        icon6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton6.png"))); // NOI18N
        icon6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon6.setMaximumSize(new java.awt.Dimension(90, 90));
        icon6.setMinimumSize(new java.awt.Dimension(90, 90));
        icon6.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        icon7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton7.png"))); // NOI18N
        icon7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon7.setMaximumSize(new java.awt.Dimension(90, 90));
        icon7.setMinimumSize(new java.awt.Dimension(90, 90));
        icon7.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, -1));

        icon9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton9.png"))); // NOI18N
        icon9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon9.setMaximumSize(new java.awt.Dimension(90, 90));
        icon9.setMinimumSize(new java.awt.Dimension(90, 90));
        icon9.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        icon8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton8.png"))); // NOI18N
        icon8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon8.setMaximumSize(new java.awt.Dimension(90, 90));
        icon8.setMinimumSize(new java.awt.Dimension(90, 90));
        icon8.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

        icon10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton10.png"))); // NOI18N
        icon10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon10.setMaximumSize(new java.awt.Dimension(90, 90));
        icon10.setMinimumSize(new java.awt.Dimension(90, 90));
        icon10.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, -1, -1));

        icon11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton11.png"))); // NOI18N
        icon11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon11.setMaximumSize(new java.awt.Dimension(90, 90));
        icon11.setMinimumSize(new java.awt.Dimension(90, 90));
        icon11.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, -1, -1));

        icon12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton12.png"))); // NOI18N
        icon12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon12.setMaximumSize(new java.awt.Dimension(90, 90));
        icon12.setMinimumSize(new java.awt.Dimension(90, 90));
        icon12.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, -1, -1));

        icon13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escudos/LauncherButton13.png"))); // NOI18N
        icon13.setAlignmentY(0.0F);
        icon13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icon13.setMaximumSize(new java.awt.Dimension(90, 90));
        icon13.setMinimumSize(new java.awt.Dimension(90, 90));
        icon13.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel3.add(icon13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 20, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 1540, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/launcherv1v1/FondoBase.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }
     private void SetImageLabel(JLabel label, String path) {
    ImageIcon icon = new ImageIcon(path);
    label.setIcon(icon); // Establece el icono sin cambiar el tamaño.
    this.repaint();      // Asegura que el componente se actualice en la pantalla.
}


    private void addMouseListeners(JLabel label) {
        label.addMouseListener(new MouseAdapter() {
            @Override
       public void mouseEntered(MouseEvent e) {
            // Aumentar el tamaño de la imagen en un 20%
            Utility.zoomImage(label, 1.2); // Asumiendo que 1.2 es un 20% más grande
        }
            @Override
            public void mouseExited(MouseEvent e) {
                Utility.resetImageSize(label);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon0;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon10;
    private javax.swing.JLabel icon11;
    private javax.swing.JLabel icon12;
    private javax.swing.JLabel icon13;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel icon6;
    private javax.swing.JLabel icon7;
    private javax.swing.JLabel icon8;
    private javax.swing.JLabel icon9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
